# This is a basic workflow to help you deploy an ADF ARM template to a higher environment

# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

on:
  workflow_dispatch:
  push:
    branches:
      - adf_publish


jobs:
  build:
    runs-on: ubuntu-latest
    name: 'This deploys to Production'
    steps:
    - uses: actions/checkout@v3
      with:
          ref: adf_publish

   
    
    - name: Azure Login
      uses: Azure/login@v2.0.0
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        
    - name: Azure PowerShell Action
      uses: Azure/powershell@v1
      with:
        # Specify the Az PowerShell script here.
        inlineScript: $triggersADF = Get-AzDataFactoryV2Trigger -DataFactoryName  "prod-demo-adf"-ResourceGroupName "vinayak-rg"
          $triggersADF | ForEach-Object { Stop-AzDataFactoryV2Trigger -ResourceGroupName vinayak-rg -DataFactoryName prod-demo-adf -Name $_.name -Force }
          
      # Azure PS version to be used to execute the script, example: 1.8.0, 2.8.0, 3.4.0. To use the latest version, specify "latest".
        azPSVersion: latest
    
    
    - name: Deploy Azure Resource Manager (ARM) Template
      uses: Azure/arm-deploy@v1.0.6
      with:
        # Provide the scope of the deployment. Valid values are: 'resourcegroup', 'managementgroup', 'subscription'
        scope: 'resourcegroup'
        # Target resource group of the deployment.
        resourceGroupName: 'vinayak-rg'
        # Specify the path to the ADF ARM template. In this scenario, the workflow is in the same branch, 
        # hence we only add the folder and arm template name to the path
        template: ./devl-demo-adf/ARMTemplateForFactory.json
        # Incremental (only add resources to resource group) or Complete (remove extra resources from resource group) or Validate (only validates the template).
        deploymentMode: Incremental
        # Supply deployment parameter values. In this simple scenario, 
        # I am only passing the name of the target ADF to which this is being deployed
        parameters: factoryName=prod-demo-adf
